---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pushoperators.vitalbh.io
  namespace: default
spec:
  group: vitalbh.io
  scope: Namespaced
  names:
    kind: PushOperator
    singular: pushoperator
    plural: pushoperators
    shortNames:
      - pushop
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                filter:
                  type: string
                  description: "Name of the filter to configure push operator"

      additionalPrinterColumns:
      - name: Spec
        type: string
        description: the filter to configure this operator
        jsonPath: .spec.filter
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: push-operator-crd
rules:
  - apiGroups:
      - vitalbh.io
    resources:
      - pushoperator
      - pushoperator/finalizers
    verbs: [ get, list, create, update, delete, deletecollection, watch ]

  - apiGroups: [ "" ]
    #
    # at the HTTP level, the name of the resource for accessing Pod
    # objects is "pods"
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "batch" ]
    #
    # at the HTTP level, the name of the resource for accessing Job
    # objects is "jobs"
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "update" ]